config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new # need to instantiate a form for
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else render 'new'
    end
  end

  def edit
    @cocktail = Cocktail.find(params[:id])  # need to instantiate a form for
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/cocktails/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h1>Cocktail's changing</h1>
      <%= simple_form_for(@cocktail) do |f| %>
          <div class="description-text">New_name</div>
          <%= f.input :name, label:false %>
          <div class="description-text">New_photo</div>
          <%= f.input :photo, as: :file, label:false,class: 'description-btn'  %>
          <%= f.submit "submit_changings", class: "description-btn"%>
        <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="container">
    <h1><em>All___Cocktails</em></h1>
    <div class="a-new">
      <%= link_to "Add___a___new___cocktail", new_cocktail_path %>
    </div>
    <div class ="cards-cocktails">
      <% @cocktails.each do |cocktail| %>
        <% if cocktail.photo.attached? %>
          <div class ="card" style="background-image:url('<%= cl_image_path cocktail.photo.key,crop: :fill %>')">
           <%# linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  %>
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div>
        <% else %>
          <div class ="card" style="background-image: url(https://images.unsplash.com/photo-1546171753-97d7676e4602?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60)">
           <%# linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  %>
            <%= link_to cocktail.name, cocktail_path(cocktail) %>
          </div> 
        <% end %>   
      <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
        <h1>New_____Cocktails</h1>

        <%= simple_form_for(@cocktail) do |f| %>
          <div class="description-text">Name</div>
          <%= f.input :name, label:false %>
          <div class="description-text">photo</div>
          <%= f.input :photo, as: :file, label:false %>
          <%= f.submit "submit the new cocktail", class: "description-btn"%>
        <% end %>
      </div>
    </div>
  </div>

app/views/cocktails/show.html.erb
<div class="container">
   <div class="row justify-content-center">
    <div class="col-12 col-lg-8">
      <!-- This div is centered and takes 6 columns -->
    

      <h1><%= @cocktail.name %></h1>

        <% if @cocktail.photo.attached? %>     
            <div class="card-show" style="background-image:url('<%= cl_image_path @cocktail.photo.key %>')" >
            <ul>
                <% @cocktail.doses.each do |dose| %>
                  <li><%= dose.description  %> - <%= dose.ingredient.name %> <%= dose.cocktail_id %> | <%= link_to "delete",dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>  
                <% end %>
              </ul>
            </div>
          <% else %>
            <div class="card-show" style="background-image:url(https://images.unsplash.com/photo-1546171753-97d7676e4602?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=400&q=60)" >
            <ul>
                <% @cocktail.doses.each do |dose| %>
                  <li><%= dose.description  %> - <%= dose.ingredient.name %> <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe ,dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %></li>  
                <% end %>
              </ul>
            </div>
        <% end %>
      <ul>
        <li><%= link_to 'Add a new Dose', new_cocktail_dose_path(@cocktail) %></li>

        <li><%= link_to "Cocktail's renaming and photo's changing", edit_cocktail_path(@cocktail) %> </li>

        <li><%= link_to "Delete #{@cocktail.name}",
                  cocktail_path(@cocktail),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %> </li>
        <li><%= link_to 'Back to all cocktails', cocktails_path %> </li>
      </ul>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
   <div class="row justify-content-center">
    <div class="col-12 col-lg-6">
      <h1>New_doses</h1>
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <div class="description-text">description</div>
      <%= f.input :description, label:false %>
      <div class="description-text">Ingredient</div>
      <%= f.association :ingredient, label:false %>
      <%= f.submit "Submit the dose", class: "description-btn" %>
      <% end %>
       <%= link_to "back to #{@cocktail.name}", cocktail_path(@cocktail) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktailReboot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>